
name: Cocoapods release
on:
  workflow_dispatch:
  release:
    
jobs:
  build:  
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push ResponderChain.podspec --allow-warnings
